"""Protocol and data types for the DiagnosisAgent abstraction.

HTTP routes call DiagnosisAgent.run(); concrete implementations live in
separate modules (e.g. anthropic_agent.py). This boundary lets us swap in
Managed Agents on Day 3 without touching HTTP callers.
"""

from dataclasses import dataclass
from typing import Protocol


class ConfigError(Exception):
    """Raised when a required configuration value (e.g. API key) is missing."""


@dataclass(frozen=True)
class AgentResponse:
    """The response returned by DiagnosisAgent.run().

    All fields are immutable once constructed.
    """

    text: str
    """Claude's completion text."""

    model: str
    """The model ID that served the request (e.g. 'claude-opus-4-7')."""

    input_tokens: int
    """Number of input tokens consumed by the request."""

    output_tokens: int
    """Number of output tokens generated by the request."""


class DiagnosisAgent(Protocol):
    """Minimal protocol for a prompt-driven AI agent.

    Callers load a named prompt template, supply variable substitutions, and
    receive a structured response. The concrete implementation is swappable —
    today it's the direct Anthropic SDK; Day 3 it may be Managed Agents.
    """

    def run(
        self,
        prompt_name: str,
        variables: dict[str, str],
        images: list[bytes] | None = None,
        max_tokens: int = 256,
    ) -> AgentResponse:
        """Run the agent with the named prompt and variable substitutions.

        Args:
            prompt_name: Name of the prompt directory under prompts/ (e.g. 'hello_world').
            variables: Key/value pairs to substitute into the prompt template.
            images: Optional list of raw image bytes to attach as image content blocks.
            max_tokens: Maximum number of tokens to generate. Defaults to 256.

        Returns:
            AgentResponse with the completion text and usage metadata.

        Raises:
            ConfigError: If a required config value (e.g. API key) is missing.
            FileNotFoundError: If the prompt file cannot be found.
            KeyError: If the prompt template references a variable not in variables.
        """
        ...
